### ISSUE TITLE
Снятие ограничения на количество звуков в .dat файлах

### ISSUE THREAD

**Issue by Favorass** [Archer-Dante/Neora#14]

**Comment by Archer-Dante** [comment]
Нет никакой информации о каком роде ограничений речь.
Заголовок - фича, тело темы - суть, воспроизведение, детали.

**Comment by Favorass** [comment]
> Нет никакой информации о каком роде ограничений речь. Заголовок - фича, тело темы - суть, воспроизведение, детали.

К сожалению, пока не могу дать никакую дополнительную информацию, т.к. изменение указано чисто в виде заголовка в фикс-листе пака darkfirenа. Возможно, стоит у него спросить подробнее.

**Comment by Archer-Dante** [comment]
Как уже говорил - если сам не сталкивался и не знаешь что это, то лучше тикет и не делать))
Временно оставлю открытым.
