### ISSUE TITLE
В Stage Mode Рудольф, принадлежащий команде 1, мерцает, когда становится невидимым, а не исчезает полностью

### ISSUE THREAD

**Issue by Favorass** [Archer-Dante/Neora#17]

**Comment by Archer-Dante** [comment]
А как должно быть?
Почему только команда 1, где это используется? Почему это баг?
По умолчанию в игре все в Stage Mode и есть команда 1, т.е. это просто фича PDK, чтобы игроки видели сами себя.

**Comment by Favorass** [comment]
> А как должно быть? Почему только команда 1, где это используется? Почему это баг? По умолчанию в игре все в Stage Mode и есть команда 1, т.е. это просто фича PDK, чтобы игроки видели сами себя.

Имеется ввиду, что для игроков Рудольф в их команде должен мерцать, когда становится невидимым, а не полностью исчезать.
Другой вопрос, что возможно это уже реализовано, нужно как-то проверить.

**Comment by Archer-Dante** [comment]
`Другой вопрос, что возможно это уже реализовано.`
В таком случае перед созданием ЛЮБОГО тикета нужно проверять сначала всё на последней версии движка. Все версии доступны для скачивания в разделе релизов.

`Когда я прожимаю скилл - то я не невидимый, а вот как выглядит это, когда прожимает бот или в мультиплеере другой игрок - нужно проверить. Ну либо подскажи, если помнишь.`
Не невидимый, а полупрозрачный. В чём проблема тогда?
Выглядит как обычная фича ПДК, которую Алькартер и упоминал в своих апдейтах.
