### ISSUE TITLE
Hitsparkи останавливаются во время паузы, а фоновая анимация карты останавливается во время таймстопа

### ISSUE THREAD

**Issue by Favorass** [Archer-Dante/Neora#19]

**Comment by Archer-Dante** [comment]
Остановка анимации карты делалась специально и отдельным кодом.
Не является багами.

**Comment by Favorass** [comment]
> Остановка анимации карты делалась специально и отдельным кодом. Не является багами.

То есть функционал для остановки анимации фона карты уже есть для таймстопа или в целом?
А что с hitsparkами? Они останавливаются во время паузы?

**Comment by Archer-Dante** [comment]
Я делал остановку фона. За остальное не отвечаю.

Формулируй задачу точнее:
В твоём заголовке вместо запроса утверждение.
Заголовок с размером описания, а нужно сделать максимально кратким и обобщающим. Например "Влияние таймстопа на неигровые объекты", и далее в теле расписывать в деталях с примерами. 
И на "Hitsparkи останавливаются во время паузы" я могу только порадоваться за них )) Здесь нет запроса или проблемы, не ясно что нужно.

В очередной раз - не нужно делать темы, не проверив ничего лично.
Это не игра в угадайку, а документирование ошибок, проблем, личных пожеланий.

**Comment by Favorass** [comment]
> з.ы. почему hitspark ? в игре есть другие спарки кроме хита?

Потому что переводил с английского на русский чейнджлог darkfirenа
